<a href="https://colab.research.google.com/github/lakshmisaibhargavi/fmml2021/blob/main/10_Problem_Solution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## The case at Madagascar. 

People are falling sick due to Covid 19 and the government wants to vaccinate the citizens who are at highest risk, on priority.
A few features that contribute to risk, has been identified alongwith their extent of contribution. The risk factors are to be calculated and measured against a threshold value. All citizens who score beyond this threshold value are to be categorised as Risk-prone.

The data given is as such:

|Person|Citizen ID | Age | Sugar Level (Blood) | Pollutant Level (Air) |
|------|-----|-----|----|----|
|1|AAA| 20 | 122 | 20 |
|2|AAB |35 | 180 | 35|
|3|ACA | 50 | 220 | 65|
|4|ABB | 70 | 300 | 30 |

Contribution of features to the disease:

|Feature|Weight|
|-------|-------|
|Age|0.05|
|Blood Sugar|0.002|
|Pollutant Level|0.02|

The high-risk people are those whose "weighted-sum of all features" falls above 4.0

FMML team members are required to develop a prototype (preferably, a python function) that works, as soon as possible, and host it on their personal GitHub account. The python function should accept input data, which would be a set of features for citizens of Madagascar, and inform which of those citizens are prone to risk.


In [1]:
# Madagascar problem

In [2]:
import numpy as np

In [3]:
A = np.array([[20, 122, 20], [35,180, 35],[50, 220, 65], [70, 300, 30]])
x = np.array([[0.05], [0.002], [0.02]])

In [4]:
# 4x3 . 3x1 = 4x1

In [5]:
y = np.matmul(A,x) - 4.0

In [6]:
Z = np.hstack((A,y))

In [7]:
Z

array([[ 2.000e+01,  1.220e+02,  2.000e+01, -2.356e+00],
       [ 3.500e+01,  1.800e+02,  3.500e+01, -1.190e+00],
       [ 5.000e+01,  2.200e+02,  6.500e+01,  2.400e-01],
       [ 7.000e+01,  3.000e+02,  3.000e+01,  7.000e-01]])

In [8]:
def RankArray(A,x):
  y = np.dot(A,x) - 4.0
  L = np.hstack((A,y))
  return L

In [9]:
print (RankArray(A,x))

[[ 2.000e+01  1.220e+02  2.000e+01 -2.356e+00]
 [ 3.500e+01  1.800e+02  3.500e+01 -1.190e+00]
 [ 5.000e+01  2.200e+02  6.500e+01  2.400e-01]
 [ 7.000e+01  3.000e+02  3.000e+01  7.000e-01]]


In [10]:
risk = RankArray(A,x)

In [12]:
prone_factor = y > 0

for i, p in enumerate(prone_factor):
  if p:
    print("Person", i+1, "is prone to risk")
  else:
    print("Person", i+1, "is not prone to risk")

Person 1 is not prone to risk
Person 2 is not prone to risk
Person 3 is prone to risk
Person 4 is prone to risk
